level_0 = {
		'terrain': './levels/0/level_0_terrain.csv',
		'crayons':'./levels/0/level_0_crayons.csv',
		'fg lights':'./levels/0/level_0_fg_lights.csv',
		'bg lights':'./levels/0/level_0_bg_lights.csv',
		'cars': './levels/0/level_0_cars.csv',
		'enemies':'./levels/0/level_0_enemies.csv',
		'constraints':'./levels/0/level_0_constraints.csv',
		'player': './levels/0/level_0_player.csv',
		'grass': './levels/0/level_0_grass.csv',
		'node_pos': (110,400),
		'unlock': 1,
		'node_graphics': './graphics/overworld/0'}
level_1 = {
		'terrain': './levels/1/level_1_terrain.csv',
		'crayons':'./levels/1/level_1_crayons.csv',
		'fg lights':'./levels/1/level_1_fg_lights.csv',
		'bg lights':'./levels/1/level_1_bg_lights.csv',
		'cars': './levels/1/level_1_cars.csv',
		'enemies':'./levels/1/level_1_enemies.csv',
		'constraints':'./levels/1/level_1_constraints.csv',
		'player': './levels/1/level_1_player.csv',
		'grass': './levels/1/level_1_grass.csv',
		'node_pos': (300,220),
		'node_graphics': './graphics/overworld/1',
		'unlock': 2}
level_2 = {
		'terrain': './levels/2/level_2_terrain.csv',
		'crayons':'./levels/2/level_2_crayons.csv',
		'fg lights':'./levels/2/level_2_fg_lights.csv',
		'bg lights':'./levels/2/level_2_bg_lights.csv',
		'cars': './levels/2/level_2_cars.csv',
		'enemies':'./levels/2/level_2_enemies.csv',
		'constraints':'./levels/2/level_2_constraints.csv',
		'player': './levels/2/level_2_player.csv',
		'grass': './levels/2/level_2_grass.csv',
		'node_pos': (480,610),
		'node_graphics': './graphics/overworld/2',
		'unlock': 3}
level_3 = {
		'terrain': './levels/3/level_3_terrain.csv',
		'crayons':'./levels/3/level_3_crayons.csv',
		'fg lights':'./levels/3/level_3_fg_lights.csv',
		'bg lights':'./levels/3/level_3_bg_lights.csv',
		'cars': './levels/3/level_3_cars.csv',
		'enemies':'./levels/3/level_3_enemies.csv',
		'constraints':'./levels/3/level_3_constraints.csv',
		'player': './levels/3/level_3_player.csv',
		'grass': './levels/3/level_3_grass.csv',
		'node_pos': (610,350),
		'node_graphics': './graphics/overworld/3',
		'unlock': 4}
level_4 = {
		'terrain': './levels/4/level_4_terrain.csv',
		'crayons':'./levels/4/level_4_crayons.csv',
		'fg lights':'./levels/4/level_4_fg_lights.csv',
		'bg lights':'./levels/4/level_4_bg_lights.csv',
		'cars': './levels/4/level_4_cars.csv',
		'enemies':'./levels/4/level_4_enemies.csv',
		'constraints':'./levels/4/level_4_constraints.csv',
		'player': './levels/4/level_4_player.csv',
		'grass': './levels/4/level_4_grass.csv',
		'node_pos': (880,210),
		'node_graphics': './graphics/overworld/4',
		'unlock': 5}
level_5 = {
		'terrain': './levels/5/level_5_terrain.csv',
		'crayons':'./levels/5/level_5_crayons.csv',
		'fg lights':'./levels/5/level_5_fg_lights.csv',
		'bg lights':'./levels/5/level_5_bg_lights.csv',
		'cars': './levels/5/level_5_cars.csv',
		'enemies':'./levels/5/level_5_enemies.csv',
		'constraints':'./levels/5/level_5_constraints.csv',
		'player': './levels/5/level_5_player.csv',
		'grass': './levels/5/level_5_grass.csv',
		'node_pos': (1050,400),
		'node_graphics':'./graphics/overworld/5',
		'unlock': 5}

levels = {
	0: level_0,
	1: level_1,
	2: level_2,
	3: level_3,
	4: level_4,
	5: level_5}